# Generated by Django 6.0.6 on 2026-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Кассир/Менеджер'), ('OPERATOR', 'Сотрудник')], default='MANAGER', max_length=20, verbose_name='Роль'),
        ),
    ]
