# Generated by Django 6.0.6 on 2026-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module',
            field=models.CharField(blank=True, choices=[('EXPRESS', 'Loko Express'), ('BUSINESS', 'Loko Business')], max_length=10, null=True, verbose_name='Направление (для директора)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Кассир/Менеджер'), ('DIRECTOR', 'Директор'), ('OPERATOR', 'Сотрудник')], default='MANAGER', max_length=20, verbose_name='Роль'),
        ),
    ]
