# Generated by Django 6.0.6 on 2026-07-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_module_alter_user_role'),
        ('finance', '0011_branch_expense_branch_otherincome_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='finance.branch', verbose_name='Филиал (для сотрудника)'),
        ),
    ]
