# Generated by Django 6.0.6 on 2026-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Кассир/Менеджер'), ('DIRECTOR', 'Директор'), ('OPERATOR', 'Сотрудник'), ('WAREHOUSE', 'Складовщик')], default='MANAGER', max_length=20, verbose_name='Роль'),
        ),
    ]
