# Generated by Django 4.2.30 on 2026-06-23 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(help_text='Главный идентификатор клиента/товара', max_length=120, verbose_name='Код клиента')),
                ('weight_kg', models.DecimalField(decimal_places=3, help_text='Поддерживаются нецелые значения, напр. 0.80, 0.53', max_digits=10, verbose_name='Вес (кг)')),
                ('places', models.PositiveIntegerField(default=1, verbose_name='Количество мест')),
                ('price_per_kg_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_rate_som', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_kg_som', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_som', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена для клиента (сом)')),
                ('cost_som', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Себестоимость (сом)')),
                ('margin_som', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Чистая выручка / маржа (сом)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Касса/банк, куда поступила оплата (нал/безнал)', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='finance.account', verbose_name='Счёт зачисления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
