# Generated by Django 4.2.30 on 2026-06-23 21:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_mode',
            field=models.CharField(choices=[('WEIGHT', 'По весу (3$ × курс)'), ('DIRECT', 'Прямая сумма')], default='WEIGHT', max_length=8, verbose_name='Режим суммы'),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_som',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма оплаты (сом)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_code',
            field=models.CharField(help_text='Главный идентификатор клиента/товара (номер или код)', max_length=120, verbose_name='Код клиента'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost_som',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Себестоимость (сом)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='margin_som',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Маржа (сом)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_som',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма начисления (сом)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Дробные значения, напр. 0.80, 0.53. Необязателен в режиме «прямая сумма».', max_digits=10, null=True, verbose_name='Вес (кг)'),
        ),
    ]
