# Generated by Django 6.0.6 on 2026-06-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0002_sale_amount_mode_sale_paid_som_sale_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_is_manual',
            field=models.BooleanField(default=False, verbose_name='Себестоимость введена вручную'),
        ),
    ]
