# Generated by Django 6.0.6 on 2026-06-29 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0003_sale_cost_is_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=120, unique=True, verbose_name='Код клиента')),
                ('price_per_kg_som', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 1 кг (сом)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цена клиента',
                'verbose_name_plural': 'Цены клиентов',
                'ordering': ('client_code',),
            },
        ),
    ]
