# Generated by Django 6.0.6 on 2026-07-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0004_clientprice'),
        ('finance', '0011_branch_expense_branch_otherincome_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Точка приёма Express (обязательно для новых продаж)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='finance.branch', verbose_name='Филиал'),
        ),
    ]
