# Generated by Django 6.0.6 on 2026-07-26 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_sale_branch'),
        ('finance', '0014_set_default_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В поиске'), ('READY', 'Готова к выдаче'), ('ISSUED', 'Выдано'), ('CANCELLED', 'Отменена')], default='NEW', max_length=12, verbose_name='Статус')),
                ('client_codes', models.JSONField(default=list, verbose_name='Коды клиентов (1–5)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий / причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Складовщик')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_orders', to='finance.branch', verbose_name='Филиал сборки')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал (оператор/менеджер)')),
                ('sales', models.ManyToManyField(blank=True, related_name='warehouse_orders', to='express.sale', verbose_name='Связанные продажи')),
            ],
            options={
                'verbose_name': 'Заявка на сборку',
                'verbose_name_plural': 'Заявки на сборку (склад)',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
