# Generated by Django 6.0.6 on 2026-07-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0006_warehouseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В поиске'), ('READY', 'Готова к выдаче'), ('NOT_FOUND', 'Не найдено'), ('ISSUED', 'Выдано'), ('CANCELLED', 'Отменена')], default='NEW', max_length=12, verbose_name='Статус'),
        ),
    ]
