# Generated by Django 6.0.6 on 2026-08-02 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0007_alter_warehouseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=120, verbose_name='Код клиента')),
                ('status', models.CharField(choices=[('IN_SEARCH', 'В поиске'), ('FOUND', 'Найдено'), ('NOT_FOUND', 'Не найдено'), ('EVENING', 'Вечерний допоиск'), ('DELIVERED', 'Выдано')], default='IN_SEARCH', max_length=12, verbose_name='Статус')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина (не найдено)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_items_found', to=settings.AUTH_USER_MODEL, verbose_name='Оприходовал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='express.warehouseorder', verbose_name='Заявка')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_item', to='express.sale', verbose_name='Продажа (создаётся при оприходовании)')),
            ],
            options={
                'verbose_name': 'Позиция заявки (склад)',
                'verbose_name_plural': 'Позиции заявок (склад)',
                'ordering': ('id',),
            },
        ),
    ]
