# Generated by Django 6.0.6 on 2026-08-18 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0009_backfill_warehouse_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Телефон (канонический)')),
                ('name', models.CharField(blank=True, max_length=160, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал (оператор/менеджер; пусто — самим клиентом)'),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='express.client', verbose_name='Клиент'),
        ),
    ]
