# Generated by Django 6.0.6 on 2026-09-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0011_employeerating'),
        ('finance', '0016_account_legacy_kargo_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход (Kargo)'),
        ),
        migrations.AddField(
            model_name='client',
            name='access_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='finance.branch', verbose_name='Регион / филиал'),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Код клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='discount',
            field=models.CharField(blank=True, max_length=16, verbose_name='Скидка (из Kargo, как есть)'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='client',
            name='legacy_kargo_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID клиента в Kargo Osh'),
        ),
        migrations.AddField(
            model_name='client',
            name='pass_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код восстановления'),
        ),
        migrations.AddField(
            model_name='client',
            name='pass_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password_bcrypt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Хеш пароля (bcrypt, из Kargo)'),
        ),
        migrations.AddField(
            model_name='client',
            name='reg_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации (Kargo)'),
        ),
        migrations.AddField(
            model_name='client',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram id'),
        ),
        migrations.AddField(
            model_name='sale',
            name='legacy_kargo_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID заказа в Kargo Osh'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки (Kargo)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Трек-номер (Kargo)'),
        ),
    ]
