# Generated by Django 6.0.6 on 2026-09-03 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0013_kargo_sync_delivery_status'),
        ('finance', '0017_branch_price_per_kg_som'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('kind', models.CharField(choices=[('INTAKE', 'Приход на склад'), ('ADJUST', 'Корректировка остатка')], default='INTAKE', max_length=8, verbose_name='Тип')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес (кг)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='finance.branch', verbose_name='Филиал')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL, verbose_name='Записал')),
            ],
            options={
                'verbose_name': 'Приход на склад (кг)',
                'verbose_name_plural': 'Приходы на склад (кг)',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
