# Generated by Django 6.0.6 on 2026-09-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0014_warehouse_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='kargo_pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в Kargoosh'),
        ),
        migrations.AddField(
            model_name='sale',
            name='kargo_sync_pending',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Ждёт отправки в Kargoosh'),
        ),
    ]
