# Generated by Django 6.0.6 on 2026-09-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0015_sale_kargo_push'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (кому засчитывается)'),
        ),
    ]
