# Generated by Django 6.0.6 on 2026-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0016_order_operator_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='origin',
            field=models.CharField(choices=[('OPERATOR', 'Сотрудник'), ('CLIENT', 'Клиент (QR)'), ('KARGO', 'Kargoosh (ожидаемые посылки)')], default='OPERATOR', max_length=8, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='status',
            field=models.CharField(choices=[('EXPECTED', 'Ожидается'), ('IN_SEARCH', 'В поиске'), ('FOUND', 'Найдено'), ('NOT_FOUND', 'Не найдено'), ('EVENING', 'Вечерний допоиск'), ('DELIVERED', 'Выдано')], default='IN_SEARCH', max_length=12, verbose_name='Статус'),
        ),
    ]
