# Generated by Django 6.0.6 on 2026-09-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0017_expected_parcels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_items_received', to=settings.AUTH_USER_MODEL, verbose_name='Оприходовал (сотрудник)'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='found_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_items_found', to=settings.AUTH_USER_MODEL, verbose_name='Нашёл (складовщик)'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='status',
            field=models.CharField(choices=[('EXPECTED', 'Ожидается'), ('IN_SEARCH', 'В поиске'), ('LOCATED', 'Найдено, к оприходованию'), ('FOUND', 'Оприходовано'), ('NOT_FOUND', 'Не найдено'), ('EVENING', 'Вечерний допоиск'), ('DELIVERED', 'Выдано')], default='IN_SEARCH', max_length=12, verbose_name='Статус'),
        ),
    ]
