# Generated by Django 6.0.6 on 2026-09-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0018_item_located_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='weight_is_estimated',
            field=models.BooleanField(default=False, verbose_name='Вес расчётный (из суммы)'),
        ),
    ]
