# Generated by Django 6.0.6 on 2026-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0019_sale_weight_is_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во мест'),
        ),
    ]
