# Generated by Django 4.2.30 on 2026-06-23 20:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('kind', models.CharField(choices=[('CASH', 'Наличные'), ('BANK', 'Банк (безналичный)')], default='CASH', max_length=10, verbose_name='Тип')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Начальный остаток')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Счёт / Касса',
                'verbose_name_plural': 'Счета / Кассы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost_per_kg_som', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость за 1 кг (сом)')),
                ('price_per_kg_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 1 кг ($)')),
                ('usd_rate_som', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Внутренний курс доллара (сом)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='finance.account', verbose_name='Со счёта')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='finance.account', verbose_name='На счёт')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OPEX', 'Операционные расходы (OpEx)'), ('SUPPLIER', 'Оплата поставщикам'), ('OTHER', 'Неоперационная деятельность (Другое)'), ('OWNER', 'Изъятие собственника (Дивиденды)')], max_length=12, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Назначение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.account', verbose_name='Счёт списания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
