# Generated by Django 4.2.30 on 2026-06-23 21:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('module', 'name'), 'verbose_name': 'Счёт / Касса', 'verbose_name_plural': 'Счета / Кассы'},
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Сом (KGS)'), ('CNY', 'Юань (CNY)')], default='KGS', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='account',
            name='module',
            field=models.CharField(choices=[('EXPRESS', 'Loko Express'), ('BUSINESS', 'Loko Business'), ('COMMON', 'Общий')], default='EXPRESS', max_length=10, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cny_to_kgs_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('12.5'), max_digits=10, verbose_name='Курс юаня для отображения (1 CNY = X сом)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='profit_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='Ставка налога на прибыль (%)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='opex_article',
            field=models.CharField(blank=True, choices=[('RENT', 'Аренда'), ('PAYROLL', 'ФОТ (Фонд оплаты труда)'), ('INCOME_TAX', 'Подоходный налог'), ('SOCIAL_FUND', 'Соц.фонд'), ('OTHER', 'Прочие расходы')], max_length=12, null=True, verbose_name='Статья OpEx'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='Курс обмена'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Сумма зачисления'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('OPEX', 'Операционные расходы (OpEx)'), ('SUPPLIER', 'Оплата поставщикам'), ('OTHER', 'Неоперационная деятельность (Другое)'), ('OWNER', 'Изъятие собственника')], max_length=12, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма списания'),
        ),
    ]
