# Generated by Django 4.2.30 on 2026-06-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_account_options_account_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма начисления'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Дата операции'),
        ),
    ]
