# Generated by Django 4.2.30 on 2026-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_paid_amount_expense_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('OPEX', 'Операционные расходы (OpEx)'), ('COGS', 'Себестоимость / закуп товара'), ('SUPPLIER', 'Оплата / аванс поставщику'), ('OTHER', 'Неоперационная деятельность (Другое)'), ('OWNER', 'Изъятие собственника')], max_length=12, verbose_name='Категория'),
        ),
    ]
