# Generated by Django 6.0.6 on 2026-06-24 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='cash_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('6'), max_digits=5, verbose_name='Налог — наличные (%)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='noncash_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=5, verbose_name='Налог — безналичные (%)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('OPEX', 'Операционные расходы (OpEx)'), ('COGS', 'Себестоимость / закуп товара'), ('SUPPLIER', 'Оплата / аванс поставщику'), ('OTHER', 'Неоперационная деятельность (Другое)'), ('OWNER', 'Изъятие собственника'), ('INVEST', 'Инвестиционная (оборудование/активы)'), ('FINANCING', 'Финансовая (кредиты/проценты)')], max_length=12, verbose_name='Категория'),
        ),
    ]
