# Generated by Django 6.0.6 on 2026-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_appsettings_cash_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_kgs_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс начального остатка (CNY)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='kgs_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс юаня (снапшот)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='kgs_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс юаня (снапшот)'),
        ),
    ]
