# Generated by Django 6.0.6 on 2026-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_backfill_kgs_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='opex_article',
            field=models.CharField(blank=True, choices=[('RENT', 'Аренда'), ('PAYROLL', 'ФОТ (Фонд оплаты труда)'), ('INCOME_TAX', 'Подоходный налог'), ('SOCIAL_FUND', 'Соц.фонд'), ('OTHER', 'Прочие расходы'), ('EQUIPMENT', 'Мебель / оборудование'), ('REPAIR', 'Ремонт помещения'), ('WAREHOUSE', 'Строительство склада'), ('LOAN_RECEIVED', 'Получение займа'), ('OWNER_CONTRIB', 'Вклад собственника'), ('LOAN_PRINCIPAL', 'Выплата займа (тело)'), ('LOAN_INTEREST', 'Выплата займа (проценты)')], max_length=14, null=True, verbose_name='Статья расхода'),
        ),
    ]
