# Generated by Django 6.0.6 on 2026-06-29 07:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_opex_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='express_cogs_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('55'), max_digits=5, verbose_name='Себестоимость Express (% от выручки)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='single_tax_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=5, verbose_name='Единый налог Express (% от выручки)'),
        ),
    ]
