# Generated by Django 6.0.6 on 2026-06-29 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_appsettings_express_cogs_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('kgs_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс юаня (снапшот)')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Источник / комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_incomes', to='finance.account', verbose_name='Счёт зачисления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прочий доход',
                'verbose_name_plural': 'Прочие доходы',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
