# Generated by Django 6.0.6 on 2026-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_seed_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Подставляется в операции без явно выбранного филиала.', verbose_name='Филиал по умолчанию'),
        ),
    ]
