# Generated by Django 6.0.6 on 2026-08-18 08:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_set_default_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Формат YYYY-MM', max_length=7, verbose_name='Месяц')),
                ('oklad', models.DecimalField(decimal_places=2, default=Decimal('20000'), max_digits=12, verbose_name='Оклад')),
                ('discipline_ok', models.BooleanField(default=True, verbose_name='Дисциплина соблюдена')),
                ('inspection_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Проверка (тайный клиент), 1–5')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Звёзды от клиентов, 1–5')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Положительных отзывов (2ГИС/Instagram)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Бонус сотрудника',
                'verbose_name_plural': 'Бонусы сотрудников',
                'ordering': ('-period', 'employee_id'),
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
