# Generated by Django 6.0.6 on 2026-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_employeebonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='legacy_kargo_card_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID кассы в Kargo Osh'),
        ),
        migrations.AddField(
            model_name='branch',
            name='legacy_kargo_region',
            field=models.CharField(blank=True, max_length=50, verbose_name='Регион в Kargo Osh'),
        ),
    ]
