# Generated by Django 6.0.6 on 2026-09-04 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_branch_price_per_kg_som'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (зарплата)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='opex_article',
            field=models.CharField(blank=True, choices=[('RENT', 'Аренда'), ('PAYROLL', 'ФОТ (Фонд оплаты труда)'), ('INCOME_TAX', 'Подоходный налог'), ('SOCIAL_FUND', 'Соц.фонд'), ('OTHER', 'Прочие расходы'), ('EQUIPMENT', 'Мебель / оборудование'), ('REPAIR', 'Ремонт помещения'), ('WAREHOUSE', 'Строительство склада'), ('PURCHASE', 'Закуп'), ('INVEST_OTHER', 'Прочее (инвестиционное)'), ('LOAN_RECEIVED', 'Получение займа'), ('OWNER_CONTRIB', 'Вклад собственника'), ('LOAN_PRINCIPAL', 'Выплата займа (тело)'), ('LOAN_INTEREST', 'Выплата займа (проценты)'), ('SINGLE_TAX', 'Единый налог')], max_length=14, null=True, verbose_name='Статья расхода'),
        ),
    ]
