# Generated by Django 4.2.30 on 2026-06-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_alter_account_options_account_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=160, verbose_name='Источник / клиент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('KGS', 'Сом (KGS)'), ('CNY', 'Юань (CNY)')], default='KGS', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('HELD', 'Принят (не признан)'), ('RECOGNIZED', 'Признан как выручка'), ('SENT_SUPPLIER', 'Отправлен поставщику')], default='HELD', max_length=14, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
                ('recognized_date', models.DateField(blank=True, null=True, verbose_name='Дата признания выручки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='finance.account', verbose_name='Счёт зачисления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Депозит',
                'verbose_name_plural': 'Депозиты',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAYABLE', 'Кредиторская (мы должны)'), ('RECEIVABLE', 'Дебиторская (нам должны)')], max_length=12, verbose_name='Тип')),
                ('counterparty', models.CharField(max_length=160, verbose_name='Контрагент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('KGS', 'Сом (KGS)'), ('CNY', 'Юань (CNY)')], default='CNY', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('CLOSED', 'Погашена')], default='OPEN', max_length=8, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженности',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
