# Generated by Django 6.0.6 on 2026-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='kgs_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс юаня (снапшот)'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='kgs_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс юаня (снапшот)'),
        ),
    ]
